<?php


namespace janami\controllers;


use common\helper\HelperFunction;
use common\models\Banners;
use common\models\MenuConfig;
use cyneek\yii2\blade\BladeBehavior;
use yii\db\Exception;
use yii\db\Expression;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

class BaseController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'blade' => [
                'class' => BladeBehavior::class
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function init()
    {
        \Yii::$app->language = 'vi-VN'; //\Yii::$app->cache->get('language');

        $globalBanners = Banners::find()
            ->where([
                'active' => Banners::BANNER_ACTIVE,
                'language' => HelperFunction::getLanguage()
            ])
            ->orderBy('id DESC')
            ->all();
        $logos = Banners::findAll([
            'active' => Banners::BANNER_ACTIVE,
            'position' => 'logo_partner'
        ]);
        $brandLogos = Banners::findAll([
            'active' => Banners::BANNER_ACTIVE,
            'position' => 'logo_brand'
        ]);
        $logoInter = Banners::findAll([
            'active' => Banners::BANNER_ACTIVE,
            'position' => 'logo_inter_partner'
        ]);
        $sliders = Banners::findAll([
            'active' => Banners::BANNER_ACTIVE,
            'position' => 'home_slider',
            'language' => HelperFunction::getLanguage()
        ]);

        $menus = MenuConfig::find()
            ->where([
                'language' => HelperFunction::getLanguage()
            ])->asArray()->all();
        \Yii::$app->params['menus'] = $menus;
        \Yii::$app->params['sliders'] = $sliders;
        \Yii::$app->params['logos'] = $logos;
        \Yii::$app->params['brands'] = $brandLogos;
        \Yii::$app->params['logoInter'] = $logoInter;
        \Yii::$app->params['globalBanners'] = $globalBanners;
        \Yii::$app->settings->invalidateCache();
        parent::init(); // TODO: Change the autogenerated stub
    }
}
