<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "galleries".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $slug
 * @property int|null $media_id
 * @property string|null $description
 * @property int|null $status
 * @property int|null $created_at
 * @property int|null $updated_at
 */
class Galleries extends BaseModel
{
    public function extraFields()
    {
        return ['avatar', 'thumbs']; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'galleries';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['media_id', 'status', 'created_at', 'updated_at'], 'integer'],
            [['description'], 'string'],
            [['name', 'slug'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'slug' => 'Slug',
            'media_id' => 'Media ID',
            'description' => 'Description',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public function getThumbs()
    {
        return $this->hasMany(Medias::className(), ['obj_id' => 'id'])
            ->andFilterWhere(['type' => Medias::GALLERY_TYPE]);
    }

    public function getAvatar()
    {
        return $this->hasOne(Medias::className(), ['obj_id' => 'media_id']);
    }
}
