<?php


namespace common\models;


use common\helper\HelperFunction;
use mdm\admin\Module;

class RbacAdmin extends Module
{
    public function init()
    {
        \Yii::$app->set('db', HelperFunction::getDb());
        parent::init(); // TODO: Change the autogenerated stub
    }

}
