<?php

namespace common\models;

use common\helper\HelperFunction;
use Yii;

/**
 * This is the model class for table "technology".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $content
 * @property string|null $avatar_id
 * @property int|null $active
 * @property string|null $type
 * @property int|null $created_at
 * @property int|null $updated_at
 */
class Technology extends BaseModel
{
    public $avatar;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'technology';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['active', 'created_at', 'updated_at', 'avatar_id'], 'integer'],
            [['name', 'content'], 'string'],
            [['type'], 'string', 'max' => 50],
            [['avatar'], 'safe']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'content' => 'Content',
            'avatar_id' => 'Avatar ID',
            'active' => 'Active',
            'type' => 'Type',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public function extraFields()
    {
        return ['avatar']; // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        if ($this->media) {
            $this->avatar = HelperFunction::getImage($this->media->path);
        }
    }

    public function getMedia()
    {
        return $this->hasOne(Medias::className(), ['id' => 'avatar_id']);
    }
}
