<?php


namespace console\controllers;


use common\helper\HelperFunction;
use yii\console\controllers\MigrateController as BasicMigrateController;


class MigrateController extends BasicMigrateController
{
public function beforeAction($action)
{
    die('HELLO');
    return parent::beforeAction($action); // TODO: Change the autogenerated stub
}

}
