name: build

on: push

env:
  CIRCLE_ARTIFACTS: ./tmp/artifact
  PROJECT_REPONAME: rnikkei-paper-viewer
jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: bash

    steps:

      - name: checkout
        uses: actions/checkout@v3

      # Create artifacts for file size reporting
      - name: Create artifacts for file size reporting
        uses: actions/upload-artifact@v3
        with:
          path: ./tmp/artifact

      # zip build project
      - name: zip release for deploy
        run: zip release.zip ./* -r

      # Save workspace for other jobs
      - name: Save workspace for other jobs
        uses: actions/upload-artifact@v3
        with:
          path: release.zip
