# This is a basic workflow to help you get started with Actions
name: build
on: push
jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
     - name: checkout
       uses: actions/checkout@v3
     
     - name: echo first
     
